name: talkng deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build and push to dockerhub
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: ndubuisijr/talkng
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Install aws cli
      uses: isbang/setup-awscli@v0.1.0
      
    - name: Deploy zip to aws s3
    - run: aws deploy push --application-name talkng --region "af-south-1" --description "This is a talk app" --ignore-hidden-files --s3-location s3://talkng-bucket/talkng.zip --source .
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        
    - name: AWS Create Deployment
      run: |
          aws deploy create-deployment \
           --application-name talkng \
           --deployment-config-name CodeDeployDefault.OneAtATime \
           --deployment-group-name talkng-group \
           --file-exists-behavior OVERWRITE \
           --s3-location bucket=talkng-bucket,key=talkng.zip,bundleType=zip \
